name: System image build
on: push
jobs:
  build:
    name: System image build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Change directory
        run: cd $GITHUB_WORKSPACE
      - name: Obtain base docker image
        run: docker pull archlinux:latest
      - name: Create docker build image
        run: docker build --no-cache -t winesapos-img-builder build/.
      - name: Build system image
        id: build_image
        run: docker run --rm -v $(pwd)/output:/workdir/output --privileged=true winesapos-img-builder:latest /bin/zsh -x scripts/winesapos-build.sh
